[feature request] add cpu burst strategy
koordinator-sh/koordinator pull request #106
Opened 2022-04-28 06:03 UTC by stormgbs

### Ⅰ. Describe what this PR does

#52 

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

2022-04-28 06:24 UTC, jasonliu747 requested changes

2022-04-28 06:24 UTC, jasonliu747 commented on apis/extension/slo-config.go
> +type NodeCPUBurstCfg struct {
we define these configs in `pkg/slo-controller/config/config.go`

2022-04-28 08:07 UTC, jasonliu747 reviewed
lgtm overall, others PTAL
/cc @eahydra @zwzhang0107 @saintube

2022-04-28 09:31 UTC, saintube reviewed
/lgtm

2022-04-28 09:47 UTC, jasonliu747 commented on pkg/slo-controller/nodeslo/nodeslo_controller_test.go
```
testingCPUBurstStrategy := util.DefaultCPUBurstStrategy()
testingCPUBurstStrategy.CFSQuotaBurstPeriodSeconds = util.Int64Ptr(60)
```

```
nodeSLOSpec := &slov1alpha1.NodeSLOSpec{
	ResourceUsedThresholdWithBE: testingResourceThresholdStrategy,
	CPUBurstStrategy:            testingCPUBurstStrategy,
}
```

2022-04-28 09:49 UTC, jasonliu747 commented on pkg/util/config.go
> +func DefaultCPUBurstConfig() slov1alpha1.CPUBurstConfig {
can you add some explanations for these default values?

2022-04-28 10:23 UTC, zwzhang0107 commented on pkg/slo-controller/nodeslo/nodeslo_controller_test.go
+1，also add 60 to testingConfigMap.

2022-04-29 06:40 UTC, jasonliu747 commented
@stormgbs Also, please rename your PR title...

2022-05-05 03:56 UTC, stormgbs commented
/close

2022-05-05 03:56 UTC, closed without merging