support numa topology policy on pod
koordinator-sh/koordinator pull request #1939
Opened 2024-03-06 07:22 UTC by KunWuLuan

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

to #1912

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2024-04-24 07:46 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +func GetNodeNUMATopologyPolicy(labels map[string]string) NumaTopologyPolicy {
这里没必要 NUMA->Numa 吧

2024-04-24 07:46 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +	// NumaTopologyPolicy represents the numa topology policy when schedule pod
ResourceSpec/ResourceStatus 目前应该主要还是 cpu、memory 这类资源，考虑到设备，NUMATopologyPolicy 这类协议是否考虑单独弄一个 Annotation Key，

2024-04-25 03:36 UTC, KunWuLuan commented on apis/extension/numa_aware.go
> +	// NumaTopologyPolicy represents the numa topology policy when schedule pod
done

2024-04-25 03:38 UTC, KunWuLuan commented on apis/extension/numa_aware.go
> +func GetNodeNUMATopologyPolicy(labels map[string]string) NumaTopologyPolicy {
done

2024-05-11 05:59 UTC, ZiMengSheng commented
这个PR 有空 rebase 一下上游哈，然后之前改动的 cpu 返回的在 restricted 策略下需要返回 preferred=true，我看只感知了节点策略，本PR 加上Pod 级别的策略后这部分逻辑没有对齐

2024-05-11 05:59 UTC, ZiMengSheng requested changes

2024-05-11 05:59 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +	NumaTopologyPolicyNone           NUMATopologyPolicy = ""
NUMA 为专有名词，没必要改的

2024-05-13 01:32 UTC, KunWuLuan commented on apis/extension/numa_aware.go
> +	NumaTopologyPolicyNone           NUMATopologyPolicy = ""
done

2024-05-13 01:33 UTC, KunWuLuan commented
Already merge the pr with upstream main. And update the policy passed to GetTopologyHints

2024-05-20 03:35 UTC, ZiMengSheng requested changes

2024-05-20 03:35 UTC, ZiMengSheng commented on pkg/scheduler/plugins/deviceshare/topology_hint.go
> +		// for resourceName, affinitySize := range minAffinitySize {
这里的注释可否直接去掉了

2024-05-20 03:35 UTC, ZiMengSheng commented on pkg/scheduler/plugins/nodenumaresource/resource_manager.go
> +	// for _, resourceName := range resourceNames {
这里同样

2024-05-20 03:35 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +	// AnnotationResourceSpec represents numa allocation API defined by Koordinator.
注释跟实际名称不匹配

2024-05-20 03:35 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +	AnnotationNumaTopologySpec = SchedulingDomainPrefix + "/numa-topology-spec"
是否用 Numa -> NUMA，AnnotationNUMATopologySpec, 跟上下文风格一致

2024-05-20 03:35 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +type NumaTopologySpec struct {
这里同样，类型和字段的风格不一致，一个Numa，一个NUMA，都用NUMA 就好了？

2024-05-20 03:35 UTC, ZiMengSheng commented on apis/extension/numa_aware.go
> +type NumaTopologyExclusive string
这里同样，都用 NUMA 就好了

2024-05-20 09:13 UTC, ZiMengSheng commented
/lgtm

2024-05-20 09:18 UTC, FillZpp commented
/approve

2024-05-20 09:24 UTC, ZiMengSheng commented
/lgtm

2024-05-20 09:25 UTC, ZiMengSheng approved these changes

2024-05-20 09:25 UTC, merged