Hook mode reconciler
koordinator-sh/koordinator pull request #319
Opened 2022-06-28 10:22 UTC by zwzhang0107

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-06-28 14:56 UTC, eahydra commented on pkg/koordlet/runtimehooks/protocol/pod_context.go
> +			klog.Infof("set pod q%v/%v bvt %v on cgroup parent %v failed, error %v", p.Request.PodMeta.Namespace,
q%v, typo?

2022-06-28 14:59 UTC, eahydra commented on pkg/koordlet/runtimehooks/reconciler/reconciler.go
> +						klog.Infof("calling reconcile function %v failed, error %v", r.description, err)
klog.Errorf?

2022-06-28 15:02 UTC, eahydra commented on pkg/koordlet/runtimehooks/reconciler/reconciler.go
> +	globalCgroupReconciler = map[ReconcilerLevel]map[string]*cgroupReconciler{
It is simpler to initialize directly when declaring variable X.

2022-06-29 05:05 UTC, jasonliu747 requested changes
Hi please set the logging level correctly according to our [conventions](https://github.com/koordinator-sh/koordinator/blob/main/docs/contributors/logging.md).

2022-06-29 06:32 UTC, zwzhang0107 commented on pkg/koordlet/runtimehooks/reconciler/reconciler.go
> +				klog.Infof("calling reconcile function %v failed, error %v", r.description, err)
use warning for some procedure failing

2022-06-29 06:40 UTC, zwzhang0107 commented
> Hi please set the logging level correctly according to our [conventions](https://github.com/koordinator-sh/koordinator/blob/main/docs/contributors/logging.md).

lines updated for this pr

2022-06-29 12:21 UTC, zwzhang0107 commented on pkg/koordlet/runtimehooks/protocol/container_context.go
> +	if _, exist := podAnnotations["io.kubernetes.docker.type"]; exist {
not yet, its a temp work around

2022-06-29 12:32 UTC, jasonliu747 reviewed
/lgtm

2022-06-29 12:40 UTC, hormes commented
/approve

2022-06-29 12:44 UTC, jasonliu747 approved these changes

2022-06-29 12:44 UTC, merged