koord-scheduler: support debug scores
koordinator-sh/koordinator pull request #604
Opened 2022-09-08 12:57 UTC by eahydra

koord-scheduler: support debug scores

Users can enable debug scores via flags -s, --debug-scores or set on demand via the following commands:

curl -X PUT <leaderSchedulerIP>:<port>/debug/flags/s --data '100'

Signed-off-by: Joseph <joseph.t.lee@outlook.com>

### Ⅰ. Describe what this PR does

Users can enable debug scores via flags -s, --debug-scores or set on demand via the following commands:

curl -X PUT <leaderSchedulerIP>:<port>/debug/flags/s --data '100'

and the scheduler will logging the following content with markdown style:

| # | Pod | Node | Score | ImageLocality | InterPodAffinity | LoadAwareScheduling | NodeAffinity | NodeNUMAResource | NodeResourcesBalancedAllocation | NodeResourcesFit | PodTopologySpread | Reservation | TaintToleration |
| --- | --- | --- | ---:| ---:| ---:| ---:| ---:| ---:| ---:| ---:| ---:| ---:| ---:|
| 0 | default/curlimage-545745d8f8-rngp7 | cn-hangzhou.10.0.4.51 | 577 | 0 | 0 | 87 | 0 | 0 | 96 | 94 | 200 | 0 | 100 |
| 1 | default/curlimage-545745d8f8-rngp7 | cn-hangzhou.10.0.4.50 | 574 | 0 | 0 | 85 | 0 | 0 | 96 | 93 | 200 | 0 | 100 |
| 2 | default/curlimage-545745d8f8-rngp7 | cn-hangzhou.10.0.4.19 | 541 | 0 | 0 | 55 | 0 | 0 | 95 | 91 | 200 | 0 | 100 |
| 3 | default/curlimage-545745d8f8-rngp7 | cn-hangzhou.10.0.4.18 | 487 | 0 | 0 | 15 | 0 | 0 | 90 | 82 | 200 | 0 | 100 |

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-09-09 02:51 UTC, eahydra commented
/hold

2022-09-09 04:04 UTC, eahydra commented
/hold cancel

2022-09-09 07:39 UTC, saintube approved these changes

2022-09-09 07:39 UTC, saintube commented on pkg/scheduler/frameworkext/framework_extender.go
> +		debugScores(debugTopNScores, pod, pluginToNodeScores, nodes)
/lgtm

2022-09-09 07:43 UTC, jasonliu747 requested changes

2022-09-09 07:43 UTC, jasonliu747 commented on pkg/util/routes/flags.go
> +			body, err := ioutil.ReadAll(req.Body)
use `io.ReadAll` instead

2022-09-09 08:10 UTC, eahydra commented on pkg/util/routes/flags.go
> +			body, err := ioutil.ReadAll(req.Body)
fixed

2022-09-09 08:53 UTC, jasonliu747 approved these changes
/lgtm

2022-09-13 01:46 UTC, hormes commented
Should this be put into a separate file, so that it may be possible to read this file through the http interface in the future?

2022-09-13 02:46 UTC, eahydra commented
> Should this be put into a separate file, so that it may be possible to read this file through the http interface in the future?

Very good advice. In fact, I have also considered this problem, but I want to provide a simple method to meet the needs of the most basic debug scores. Later, we will look at the feedback and needs of the community before deciding how to persist and query the results.

2022-09-13 12:21 UTC, hormes commented
/approve

2022-09-13 12:22 UTC, merged