Interference detection support
koordinator-sh/koordinator pull request #622
Opened 2022-09-16 03:28 UTC by songtao98

Signed-off-by: songtao98 <songtao2603060@gmail.com>

### Ⅰ. Describe what this PR does
This PR is for koordinator interference detection support. Code will be commited continuously and this PR will be hold for a certain period. 

### Ⅱ. Does this pull request fix one issue?
#451 

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-09-16 03:28 UTC, songtao98 commented
/hold

2022-09-20 11:56 UTC, songtao98 commented on pkg/util/perf.go
> +	err = hwProfiler.Profile(profile)
the newest commit fix this: between profile.Start() and profile.Stop(), use <-time.After() to set a 10 seconds interval

2022-09-21 07:07 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/api.go
> +	MetricValue interface{}
need convert function for different metric name

2022-09-29 09:01 UTC, zwzhang0107 commented on pkg/util/perf.go
> +			if err != nil {
should return error

2022-09-29 09:13 UTC, zwzhang0107 commented on pkg/util/perf.go
> +	timer := time.NewTicker(10 * time.Second)
// TODO the 10 seconds is configurable

2022-10-11 10:58 UTC, jasonliu747 commented
/unhold

2022-10-11 11:15 UTC, saintube commented on pkg/koordlet/metricsadvisor/collector.go
> +	go util.RunFeature(func() {
`util.RunFeature` will start a new goroutine itself

2022-10-11 11:37 UTC, saintube commented on pkg/koordlet/metriccache/metric_cache.go
> +	MetricNamePodCPI       InterferenceMetricName = "PodCPI"
is PodCPI not implemented?

2022-10-11 11:37 UTC, saintube commented on pkg/koordlet/metriccache/api.go
> +	ObjectID    string
does the `ObjectID` map into a pod or a container? please add some comments

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/api.go
> +	ObjectID    string
ContainerID string
PodUID string

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/metric_cache.go
> +func (m *metricCache) GetInterferenceMetric(metricName InterferenceMetricName, objectID *string, param *QueryParam) InterferenceQueryResult {
GetContainerInterferenceMetric

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/api.go
> +type InterferenceMetric struct {
ContainerInterferenceMetric

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/metric_cache.go
> +	switch metric.MetricName {
insertCPIMetric
mv switch outside

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/metric_cache_test.go
> +				aggregateArg: AggregationTypeLast,
we need more tests with different aggregateArgs

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metricsadvisor/config.go
> +	fs.IntVar(&c.CollectInterferenceIntervalSeconds, "collect-interference-interval-seconds", c.CollectInterferenceIntervalSeconds, "Collect interference interval by seconds")
consider use fs.Duration

2022-10-11 12:59 UTC, zwzhang0107 commented on pkg/koordlet/metricsadvisor/config.go
> +		CollectInterferenceIntervalSeconds:   60,
PerformanceCollectorInterval

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/koordlet/metricsadvisor/collector.go
> +			os.Exit(1)
klog.Fatal will include os.Exit

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/koordlet/metricsadvisor/collector.go
> +		ic := NewPerformanceCollector(&c.statesInformer, &c.metricCache, c.config.CollectInterferenceTimeWindowSeconds)
mv NewPerformanceCollector out from run interval

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/util/perf/perf.go
> +			return
using same style:
return result, err

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/util/perf/perf.go
> +/*
need go build tag of linux

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/util/perf/perf.go
> +		if err = (*c.cpuHwProfilersMap[cpu]).Start(); err != nil {
use go run to start async at the same time

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/util/stat.go
> +	defer unix.Close(containerCgroupFd)
close only if not closed by profiler

2022-10-13 03:43 UTC, zwzhang0107 commented on pkg/util/perf/perf.go
> +	if err := (*c.cpuHwProfilersMap[cpu]).Close(); err != nil {
open a new fd for each cpu profiler?
in case of fd was double closed

2022-10-19 12:19 UTC, zwzhang0107 commented on pkg/koordlet/metriccache/metric_cache.go
> +	case MetricNamePodCPI:
same logic with MetricNameContainerCPI, which can be merged

2022-10-19 12:19 UTC, zwzhang0107 commented on pkg/koordlet/metricsadvisor/config.go
> +	fs.IntVar(&c.PerformanceCollectorIntervalSeconds, "collect-interference-interval-seconds", c.PerformanceCollectorIntervalSeconds, "Collect interference interval by seconds")
consider using fs.DurationVar

2022-10-24 04:16 UTC, hormes commented on pkg/koordlet/metricsadvisor/performance_collector_linux.go
> +	timer := time.NewTicker(time.Duration(c.collectTimeWindow) * time.Second)
looks like timer should be used, not ticker

2022-10-24 04:17 UTC, hormes commented on pkg/koordlet/metricsadvisor/performance_collector_linux.go
> +	timer := time.NewTicker(time.Duration(c.collectTimeWindow) * time.Second)
or time.Sleep(10*time.Second)

2022-10-25 08:05 UTC, jasonliu747 requested changes
![image](https://user-images.githubusercontent.com/24452340/197718394-edf2c9a3-f8f9-4320-91f4-42190e32559e.png)

2022-10-27 07:33 UTC, zwzhang0107 commented
/lgtm

2022-10-28 08:56 UTC, jasonliu747 approved these changes
/lgtm

2022-10-28 08:56 UTC, merged