bugfix: not report when no gpu device
koordinator-sh/koordinator pull request #636
Opened 2022-09-19 08:27 UTC by ZYecho

Signed-off-by: Yue Zhang <huaihuan.zy@alibaba-inc.com>

### Ⅰ. Describe what this PR does

fix #618 
### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-09-19 08:56 UTC, jasonliu747 commented on pkg/slo-controller/noderesource/noderesource.go
>  	memoryTotal := resource.NewQuantity(0, resource.DecimalSI)
`memoryTotal` should be shown in BinarySI format, and `coreTotal` should be DecimalSI

2022-09-19 08:56 UTC, jasonliu747 commented on pkg/util/resource.go
> +	if !oldExist {
are you sure? why?

2022-09-19 09:05 UTC, jasonliu747 commented on pkg/slo-controller/noderesource/noderesource.go
> +	if device == nil || len(device.Spec.Devices) == 0 {
Devices 长度不等于 0⃣️ 的情况下，也不一定会包含 GPU

2022-09-19 09:05 UTC, jasonliu747 requested changes

2022-09-19 09:05 UTC, jasonliu747 commented on pkg/slo-controller/noderesource/noderesource.go
> +	if device == nil || len(device.Spec.Devices) == 0 {
Devices 长度不等于 0⃣️ 的情况下，也不一定会包含 GPU

2022-09-19 12:48 UTC, hormes commented on pkg/slo-controller/noderesource/noderesource.go
> +	if device == nil || len(device.Spec.Devices) == 0 {
rdma 等设备会不会出现在这里

2022-09-19 12:51 UTC, hormes commented on pkg/util/resource.go
> +	if !oldExist {
看起来相当于是 old, new 都不存在的情形，这个写法逻辑没问题，但容易让人困惑，建议改成：
if !oldExist && !newExist {
  return nil
}

2022-09-20 07:44 UTC, zwzhang0107 commented
/lgtm

2022-09-20 08:19 UTC, jasonliu747 commented
/lgtm cancel

2022-09-20 09:41 UTC, jasonliu747 commented on pkg/koordlet/statesinformer/states_device_linux.go
> +	if len(gpuDevices) == 0 {
这里直接return确实可以work，但合适吗😂

2022-09-21 02:49 UTC, jasonliu747 approved these changes
/lgtm
others PTAL

2022-09-21 04:04 UTC, hormes commented
/approve

2022-09-21 04:04 UTC, merged