koord-manager: modify quota-webhook
koordinator-sh/koordinator pull request #660
Opened 2022-09-26 13:22 UTC by xulinfei1996

Signed-off-by: xulinfei.xlf <xulinfei.xlf@alibaba-inc.com>

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-09-27 03:07 UTC, jasonliu747 requested changes

2022-09-27 03:07 UTC, jasonliu747 commented on Makefile
> -REG ?= ghcr.io
please remove this from your commit.

2022-09-27 04:02 UTC, xulinfei1996 commented on Makefile
> -REG ?= ghcr.io
fixed

2022-09-28 02:44 UTC, buptcozy approved these changes
/LGTM

2022-09-28 08:00 UTC, eahydra approved these changes
/lgtm
/approve

2022-10-08 02:57 UTC, hormes commented
/approve

2022-10-08 08:46 UTC, hormes commented
/lgtm

2022-10-08 14:06 UTC, buptcozy approved these changes
/lgtm

2022-10-08 15:25 UTC, jasonliu747 approved these changes
/lgtm

2022-10-08 15:25 UTC, merged