koordlet: add gc logs for metric cache
koordinator-sh/koordinator pull request #749
Opened 2022-10-27 12:54 UTC by zwzhang0107

### Ⅰ. Describe what this PR does

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Describe how to verify it

### Ⅳ. Special notes for reviews

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

2022-10-27 13:06 UTC, saintube commented
/lgtm

2022-10-27 13:08 UTC, saintube requested changes

2022-10-27 13:08 UTC, saintube commented on pkg/koordlet/metriccache/storage_test.go
> +				t.Errorf("CountPodResourceMetric got error %v", err)
UT failed

2022-10-31 02:33 UTC, saintube approved these changes

2022-10-31 02:33 UTC, saintube commented on pkg/koordlet/metriccache/metric_cache.go
> +	klog.V(4).Infof("expired metric data before %v has been recycled, remaining in db size: "+
/lgtm

2022-10-31 02:46 UTC, jasonliu747 approved these changes
/lgtm

2022-10-31 14:01 UTC, merged